version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_fitlife
      MYSQL_USER: api_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3305:3306"
